name: Move Issue to In Review

on:
  pull_request:
    types: [opened, reopened]

jobs:
  move-to-in-review:
    runs-on: ubuntu-latest
    steps:
      - name: Extract Issue Number from PR Body
        id: extract_issue
        run: |
          ISSUE_NUMBER=$(echo "${{ github.event.pull_request.body }}" | grep -oE '#[0-9]+' | tr -d '#')
          echo "issue_number=$ISSUE_NUMBER" >> $GITHUB_ENV

      - name: Move Issue to In Review
        if: ${{ env.issue_number != '' }}
        uses: actions/github-script@v6
        with:
          script: |
            const issue_number = process.env.issue_number;
            const project_id = '12053499';
            const column_id = '47fc9ee4';
            
            const issue = await github.rest.issues.get({
              owner: context.repo.owner,
              repo: context.repo.repo,
              issue_number: issue_number,
            });

            if (issue) {
              await github.rest.projects.updateCard({
                card_id: issue.data.node_id,
                column_id: column_id,
              });
            }
