name: Build, Push, Deploy Cachee API

on:
    push:
        branches:
            - main
        paths:
            - "backend/**"

jobs:
    build:
        runs-on: ubuntu-latest
        permissions:
            contents: read
            packages: write

        steps:
            - uses: actions/checkout@v4

            - name: Log in to GHCR
              uses: docker/login-action@v3
              with:
                  registry: ghcr.io
                  username: ${{ github.actor }}
                  password: ${{ secrets.GITHUB_TOKEN }}

            - name: Build and push
              uses: docker/build-push-action@v5
              with:
                  context: ./backend
                  push: true
                  tags: ghcr.io/${{ github.repository }}/backend:latest

            - name: Deploy on VPS
              uses: appleboy/ssh-action@v1.1.0
              with:
                  host: ${{ secrets.VPS_HOST }}
                  username: ${{ secrets.VPS_USER }}
                  key: ${{ secrets.VPS_SSH_KEY }}
                  script: |
                      docker login ghcr.io -u ${{ github.repository_owner }} -p ${{ secrets.VPS_GHCR_PAT }}
                      docker pull ghcr.io/${{ github.repository }}/backend:latest
                      docker stop ${{ vars.API_CONTAINER_NAME }} || true
                      docker rm ${{ vars.API_CONTAINER_NAME }} || true
                      docker run -d -e DATABASE_URL="${{ secrets.ENV_DATABASE_URL }}" -e PORT="${{ vars.API_PORT }}" -e JWT_KEY="${{ secrets.ENV_JWT_KEY }}" -e NODE_ENV="${{ vars.NODE_ENV }}" --name ${{ vars.API_CONTAINER_NAME }} --network ${{ vars.DOCKER_NETWORK_NAME }} -p ${{ vars.API_PORT }}:${{ vars.API_PORT }} --restart unless-stopped ghcr.io/${{ github.repository }}/backend:latest
